# Site settings
title: Keith Wasielewski
email: binaryLunchbox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site for all things web development, technology,
  and games that interest Keith Wasielewski. Sometimes helpful.
  Sometimes insightful. Always entertaining.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.binarylunchbox.com" # the base hostname & protocol for your site
twitter_username: BluestarNEO
github_username:  BluestarNEO

# Build settings
markdown: kramdown
